version: '3.1'
services:
  api:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
     MYSQL_PASSWORD: example_password
     MYSQL_USER: parkman
     MYSQL_DATABASE: parkman_db
     MYSQL_RANDOM_ROOT_PASSWORD: 1